/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import Controller.AlumnosController;
import Controller.CursosController;
import Controller.ProfesoresController;
import DataAccess.GlobalException;
import DataAccess.NoDataException;
import Model.AlumnosModel;
import Model.CursosModel;
import Model.ProfesoresModel;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import matriculadesktop.Application;

/**
 *
 * @author guill
 */
public class AlumnosView extends javax.swing.JInternalFrame implements Observer {
    private AlumnosController controller;
    private AlumnosModel model;

    /**
     * Creates new form CursosView
     */
    public AlumnosView() {
        initComponents();
        controlDeUsuario();
    }
    
    public void setController(AlumnosController controller) {
        this.controller = controller;
    }

    public void setModel(AlumnosModel model) {
        this.model = model;
        model.addObserver(this);
    }

    public AlumnosController getController() {
        return controller;
    }

    public AlumnosModel getModel() {
        return model;
    }
    
    public void controlDeUsuario() {
        String u = Application.LOGIN.getController().sesion();
        //u = "Alumno";
        switch (u) {
            case "Alumno":
                LabelMantenimientos.setVisible(false);
                ButtonEditar.setVisible(false);
                ButtonEliminar.setVisible(false);
                ButtonIngresar.setVisible(false);
                break;
            case "Profesor":
                break;
            case "Administrador":
                break;
            case "Matriculador":
                break;
            default:
                //ItemAlumnos.setVisible(true);
                break;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bG = new javax.swing.ButtonGroup();
        TFBusqueda = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ButtonBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        ButtonIngresar = new javax.swing.JButton();
        LabelMantenimientos = new javax.swing.JLabel();
        ButtonEditar = new javax.swing.JButton();
        ButtonEliminar = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        jLabel1.setText("Realizar busqueda por:");

        ButtonBuscar.setText("Buscar");
        ButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuscarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        bG.add(jRadioButton1);
        jRadioButton1.setText("Nombre del alumno");

        bG.add(jRadioButton2);
        jRadioButton2.setText("Cédula del alumno");

        bG.add(jRadioButton3);
        jRadioButton3.setText("Código de carrera");

        ButtonIngresar.setText("Ingresar nuevo alumno");
        ButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonIngresarActionPerformed(evt);
            }
        });

        LabelMantenimientos.setText("Mantenimientos:");

        ButtonEditar.setText("Editar alumno existente");
        ButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditarActionPerformed(evt);
            }
        });

        ButtonEliminar.setText("Eliminar un alumno");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton3)
                        .addGap(36, 36, 36)
                        .addComponent(TFBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelMantenimientos)
                        .addGap(39, 39, 39)
                        .addComponent(ButtonIngresar)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonEditar)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonEliminar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(TFBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonBuscar)
                    .addComponent(jRadioButton3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonIngresar)
                    .addComponent(LabelMantenimientos)
                    .addComponent(ButtonEditar)
                    .addComponent(ButtonEliminar))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuscarActionPerformed
        try {
            //jRadioButton1.getText();
            jRadioButton1.setActionCommand("NA");
            jRadioButton2.setActionCommand("CA");
            jRadioButton3.setActionCommand("CC");            
            
            controller.buscarAlumnos();
            
            if(model.getMensaje()!=""){
                JOptionPane.showMessageDialog(null,model.getMensaje());
                model.clearErrors();
            }
        }catch(Exception e){
            System.err.printf("ERROR EN ALUMNOS CONTROLLER");
            JOptionPane.showMessageDialog(null,"Excepción");
            
        }
    }//GEN-LAST:event_ButtonBuscarActionPerformed

    private void ButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonIngresarActionPerformed
        // TODO add your handling code here:
        AlumnoView av = Application.ALUMNOVIEW;
        av.getController().setAccion("Ingresar");
        av.setTextoAccion("Ingresar");
        av.setVisible(true);
        Application.CONTENEDOR.setEnabled(false);
    }//GEN-LAST:event_ButtonIngresarActionPerformed

    private void ButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditarActionPerformed
        // TODO add your handling code here:
        AlumnoView av = Application.ALUMNOVIEW;
        av.getController().setAccion("Editar");
        av.setTextoAccion("Editar");
        av.setVisible(true);
        Application.CONTENEDOR.setEnabled(false);
    }//GEN-LAST:event_ButtonEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBuscar;
    private javax.swing.JButton ButtonEditar;
    private javax.swing.JButton ButtonEliminar;
    private javax.swing.JButton ButtonIngresar;
    private javax.swing.JLabel LabelMantenimientos;
    public javax.swing.JTextField TFBusqueda;
    public javax.swing.ButtonGroup bG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        this.jTable1.setModel(model.getAlumnos());
    }
}
