/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import javax.security.auth.login.AppConfigurationEntry;
import matriculadesktop.Application;

/**
 *
 * @author guill
 */
public class AppView extends javax.swing.JFrame {

    /**
     * Creates new form AppView
     */
    public AppView() {
        //this.setLocationRelativeTo(null);
        initComponents();
        this.setTitle("Gestión Académica");
        controlDeUsuario();
    }
    
    public void controlDeUsuario(){
        String u = Application.LOGIN.getController().sesion();
        //u = "Alumno";
        switch(u){
            case "Alumno":
                ItemProfesores.setVisible(false);
                break;
            case "Profesor":
                break;
            case "Administrador":
                break;
            case "Matriculador":
                break;
            default:
                //ItemAlumnos.setVisible(true);
                break;
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenedor = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        ItemCursos = new javax.swing.JMenu();
        ItemProfesores = new javax.swing.JMenu();
        ItemCarreras = new javax.swing.JMenu();
        ItemAlumnos = new javax.swing.JMenu();
        ItemSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout ContenedorLayout = new javax.swing.GroupLayout(Contenedor);
        Contenedor.setLayout(ContenedorLayout);
        ContenedorLayout.setHorizontalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1045, Short.MAX_VALUE)
        );
        ContenedorLayout.setVerticalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
        );

        ItemCursos.setText("Cursos");
        ItemCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ItemCursosMouseClicked(evt);
            }
        });
        jMenuBar1.add(ItemCursos);

        ItemProfesores.setText("Profesores");
        ItemProfesores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ItemProfesoresMouseClicked(evt);
            }
        });
        jMenuBar1.add(ItemProfesores);

        ItemCarreras.setText("Carreras");
        ItemCarreras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ItemCarrerasMouseClicked(evt);
            }
        });
        jMenuBar1.add(ItemCarreras);

        ItemAlumnos.setText("Alumnos");
        ItemAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ItemAlumnosMouseClicked(evt);
            }
        });
        jMenuBar1.add(ItemAlumnos);

        ItemSalir.setText("Salir");
        ItemSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ItemSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(ItemSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItemCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItemCursosMouseClicked
        // TODO add your handling code here:
        Application.CURSOSVIEW.setVisible(true);
    }//GEN-LAST:event_ItemCursosMouseClicked

    private void ItemProfesoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItemProfesoresMouseClicked
        // TODO add your handling code here:
        Application.PROFESORESVIEW.setVisible(true);
    }//GEN-LAST:event_ItemProfesoresMouseClicked

    private void ItemCarrerasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItemCarrerasMouseClicked
        // TODO add your handling code here:
        Application.CARRERASVIEW.setVisible(true);
    }//GEN-LAST:event_ItemCarrerasMouseClicked

    private void ItemAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItemAlumnosMouseClicked
        // TODO add your handling code here:
        Application.ALUMNOSVIEW.setVisible(true);        
    }//GEN-LAST:event_ItemAlumnosMouseClicked

    private void ItemSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItemSalirMouseClicked
        // TODO add your handling code here:
        Application.LOGIN.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ItemSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane Contenedor;
    private javax.swing.JMenu ItemAlumnos;
    private javax.swing.JMenu ItemCarreras;
    private javax.swing.JMenu ItemCursos;
    private javax.swing.JMenu ItemProfesores;
    private javax.swing.JMenu ItemSalir;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
